version: "3.7"

services:
  autenticador:
    image: autenticador
    container_name: autenticador
    build: ./autenticador
    depends_on:
      - db_usuarios
    environment:
      HOST_PG: db_usuarios
      PASSWORD_PG: teste
      USER_PG: teste
      DATABASE_PG: teste
      PORTA_PG: 5432
      CHAVE_JWT: dsadjsdidsondsongds5485161sd1fsd3fdsf1dsf
      APP_HOST: localhost:3000
    ports:
      - 3000:3000
    command: "npm start"
    networks:
      - backend

  boletos:
    image: boletos
    container_name: boletos
    build: ./boletos
    depends_on:
      - db_boletos
    environment:
      HOST_MYSQL: db_boletos
      PASSWORD_MYSQL: root
      USER_MYSQL: root
      DATABASE_MYSQL: boletos
      PORTA_MYSQL: 3306
      APP_HOST: localhost:3001
    ports:
      - 3001:3000
    command: "npm start"
    networks:
      - backend

  db_usuarios:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: teste
      POSTGRES_USER: teste
      POSTGRES_DB: teste
    ports:
      - 5432:5432
    networks:
      - backend

  db_boletos:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boletos
    ports:
      - 3306:3306
    networks:
      - backend

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.203.192/27
