version: "3.7"

services:
  gateway:
    image: autenticador
    container_name: autenticador
    build: .
    depends_on:
      - db
    environment:
      HOST_PG: db
      PASSWORD_PG: teste
      USER_PG: teste
      DATABASE_PG: teste
      PORTA_PG: 5432
      CHAVE_JWT: dsadjsdidsondsongds5485161sd1fsd3fdsf1dsf
      APP_HOST: localhost:3000
    ports:
      - 3000:3000
    command: "npm start"
    networks:
      - backend

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: teste
      POSTGRES_USER: teste
      POSTGRES_DB: teste
    ports:
      - 5432:5432
    networks:
      - backend

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.203.192/27
